### ISSUE TITLE
When using UseStaticFiles, the rate is fixed at 16kb/s when it is attached to the global speed limit by unchecking the condition.

### ISSUE THREAD

**Issue by degagetech** [david-acker/ThrottlingSample#5]
Thank you very much for the help of your code, but there seems to be a problem where the restriction is invalid when using UseStaticFiles.

I tried to make this method work for all responses by changing the criteria for this method to look like this:

`  return InvokeCore(context, 200_000);
        //var downloadThrottlingMetadata = 
        //    context.GetEndpoint()?.Metadata?.GetMetadata<IDownloadThrottlingMetadata>();

        //return downloadThrottlingMetadata?.MaxBytesPerSecond is not { } maxBytesPerSecond 
        //    ? _next(context) 
        //    : InvokeCore(context, maxBytesPerSecond);`

Then I tried to limit the rate to no effect, and all static file responses were limited to 16kb/s.

**Comment by david-acker** [comment]
Good catch. I hadn’t considered how this would work in regards to static files.

For the issue with the rate limiting having no effect, it sounds like an issue with the order of the middleware could be at play. Do you have your call to `UseDownloadThrottling` before or after `UseStaticFiles`? I just confirmed locally that the downloading throttling only is applied if `UseDownloadThrottling` is called before:

```csharp
app.UseDownloadThrottling();
app.UseStaticFiles(…);
```

But it looks like we’ll need some separate handling for static file request alongside the middleware, since these static files requests are independent from the initial request that they’re “associated” with (e.g. the request for a Razor page). So unfortunately we won’t be able to get the specified rate limit via the endpoint like the middleware currently does. 

This just a rough idea, but perhaps something along the lines of this could work? When I get a chance, I’ll do some more testing and refine this idea a bit.

```csharp
app.UseStaticFiles(new StaticFileOptions()
{
    OnPrepareResponse = (context) =>
    {
	var maxBytesPerSecond = 100_000;

        var originalBody = context.Context.Response.Body;
        var throttledBody = new ThrottledStream(originalBody, maxBytesPerSecond);
        context.Context.Response.Body = throttledBody;

        context.Context.Response.OnStarting(() =>
        {
            context.Context.Response.Body = throttledBody;
            return Task.CompletedTask;
        });

        context.Context.Response.OnCompleted(async () =>
        {
            context.Context.Response.Body = originalBody;
            await throttledBody.DisposeAsync();
        });
    }
});
```

**Comment by degagetech** [comment]
I modified part of the ThrottledStream logic, and now the response to static files is also valid, modified as follows:

```
    private DateTime? _beginTime;
    public override async Task WriteAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
    {
        var start = offset;
        var remainingBytes = count;
        if (!_beginTime.HasValue)
        {
            _beginTime = DateTime.UtcNow;
        }
        while (remainingBytes > 0)
        {
            var newBytesWritten = Math.Min(remainingBytes, _maxBytesPerSecond);

            await ThrottleAsync(newBytesWritten, cancellationToken);
            await _innerStream.WriteAsync(buffer.AsMemory(start, newBytesWritten), cancellationToken);

            start += newBytesWritten;
            remainingBytes -= newBytesWritten;
        }
    }
    private async Task ThrottleAsync(int newBytesWritten, CancellationToken cancellationToken = default)
    {
        _bytesWritten += newBytesWritten;
        var elapsed = DateTime.UtcNow - _beginTime.Value;
        var bytesPerSecond = _bytesWritten / elapsed.TotalSeconds;
        if (_bytesWritten> _maxBytesPerSecond && bytesPerSecond >= _maxBytesPerSecond)
        {
            var realTime = (_bytesWritten*1.0d / _maxBytesPerSecond) * 1000; 
            var delayMilliseconds = (int)(realTime - elapsed.TotalMilliseconds);
            await Task.Delay(delayMilliseconds, cancellationToken);
        }
        //_bytesWritten += newBytesWritten;

        //var elapsed = DateTime.UtcNow - _lastWriteTime;
        //var bytesPerSecond = _bytesWritten / elapsed.TotalSeconds;

        //if (bytesPerSecond >= _maxBytesPerSecond)
        //{
        //    var delayMilliseconds = (int)(1_000 - elapsed.TotalMilliseconds);
        //    await Task.Delay(delayMilliseconds, cancellationToken);
        //}

        //_bytesWritten = 0;
        //_lastWriteTime = DateTime.UtcNow;
    }
```
Thanks again for helping me with your code.
